
package org.sample.ws;

import javax.xml.namespace.*;
import javax.xml.ws.*;
import java.net.*;
import java.util.logging.*;


/**
 * WSDL File for HelloService
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "Hello_Service", targetNamespace = "http://www.examples.com/wsdl/HelloService.wsdl", wsdlLocation = "http://localhost:8080/webservice-1.0.0/hello?wsdl")
public class HelloService
    extends Service
{

    private final static URL HELLOSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(HelloService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = HelloService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/webservice-1.0.0/hello?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/webservice-1.0.0/hello?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        HELLOSERVICE_WSDL_LOCATION = url;
    }

    public HelloService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloService() {
        super(HELLOSERVICE_WSDL_LOCATION, new QName("http://www.examples.com/wsdl/HelloService.wsdl", "HelloWebServiceService"));
    }

    /**
     * 
     * @return
     *     returns HelloPortType
     */
    @WebEndpoint(name = "Hello_Port")
    public HelloPortType getHelloPort() {
        return super.getPort(new QName("http://www.examples.com/wsdl/HelloService.wsdl", "Hello_Port"), HelloPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloPortType
     */
    @WebEndpoint(name = "Hello_Port")
    public HelloPortType getHelloPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.examples.com/wsdl/HelloService.wsdl", "Hello_Port"), HelloPortType.class, features);
    }

}
