
package org.sample.ws;

import javax.jws.*;
import javax.jws.soap.*;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Hello_PortType", targetNamespace = "http://www.examples.com/wsdl/HelloService.wsdl")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface HelloPortType {


    /**
     * 
     * @param firstName
     * @return
     *     returns java.lang.String
     */
    @WebMethod
//    @WebResult(name = "greeting", partName = "greeting")
    public String sayHello(
        @WebParam(name = "firstName", partName = "firstName")
        String firstName);

}
